using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;

namespace AssetManagement.DataAccessLibrary.DataModels
{
    public sealed class ComputerData
    {
        /// <summary>
        ///     This constructor can construct this object from a line of csv data,
        ///     which is provided by PC-ID.
        /// </summary>
        /// <param name="fileName">The name of the file.</param>
        /// <param name="separator">The char which separates the fields in the csvLine. This is usually ',' or ';'.</param>
        /// <param name="cultureInfo">Tells the method how to parse the Timestamp</param>
        /// <param name="csvLine">A string of fields separated by the separator parameter.</param>
        public ComputerData(string fileName, char separator, CultureInfo cultureInfo, string csvLine)
        {
            string[] fields = csvLine.Split(separator);
            FileName = fileName;
            //TODO: See notion task - fix datetime conversion.
            Timestamp = DateTime.Now; //Convert.ToDateTime(fields[0], cultureInfo);
            Username = fields[1];
            Holder = fields[2];
            Department = fields[3];
            PcName = fields[4];
            OperatingSystem = fields[5];
            Manufacturer = fields[6];
            Model1 = fields[7];
            Model2 = fields[8];
            SerialNumber = fields[9];
            PcadStatus = fields[10];
        }

        public ComputerData()
        {
        }

        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Mark ID as auto-generated by SQL database
        public string Id { get; set; }

        public string FileName { get; set; }
        public string PcName { get; set; }
        public DateTime Timestamp { get; set; }
        public string Holder { get; set; }
        public string Username { get; set; }
        public string Department { get; set; }
        public string OperatingSystem { get; set; }
        public string Manufacturer { get; set; }
        public string Model1 { get; set; }
        public string Model2 { get; set; }
        public string SerialNumber { get; set; }
        public string PcadStatus { get; set; }

        public override string ToString() => $"{Timestamp}: Holder: {Holder}, PcName: {PcName}";

        public static explicit operator Computer(ComputerData data)
        {
            AssetHolder holder = new AssetHolder(data.Holder, data.Username, data.Department);
            return new Computer(data.PcName, data.OperatingSystem, data.Manufacturer, data.Model1, data.SerialNumber);
        }
    }
}